repos:
-   repo: git@github.com:pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
-   repo: git@github.com:psf/black.git
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.9
